// ── SCHEDULE DATA ──
// Edit this file to update match results, times, venues, and opponents.
// result: "win" | "lose" | null    — null if not yet played
// tbd: true | null                 — true if time is a slot (e.g. "2nd Game PM"), null if exact time
// score: { site: X, opp: Y }      — fill in both to show score on overlay; null to hide
// stage: "semis" | "finals" | "3rd" | null

const SCHEDULE_DATA = {
  days: [
    {
      day: 18,
      name: "Wednesday",
      date: "March 18, 2026",
      sections: [
        {
          sport: "basketball",
          icon: "ico-basketball",
          label: "Basketball — Men (5v5)",
          venue: "Leisure Coast Gym",
          highlight: null,
          matches: [
            {
              time: "2:30 PM",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 80, opp: 93 },
            },
          ],
        },
        {
          sport: "volleyball",
          icon: "ico-volleyball",
          label: "Volleyball — Men",
          venue: "Leisure Coast Court 1",
          highlight: null,
          matches: [
            {
              time: "2nd Game PM",
              tbd: true,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 2, opp: 1 },
            },
          ],
        },
        {
          sport: "volleyball",
          icon: "ico-volleyball",
          label: "Volleyball — Women",
          venue: "Leisure Coast Court 2",
          highlight: null,
          matches: [
            {
              time: "2nd Game PM",
              tbd: true,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 2, opp: 0 },
            },
          ],
        },
        {
          sport: "beach",
          icon: "ico-beach",
          label: "Beach Volleyball — Men",
          venue: "Sand Area",
          highlight: null,
          matches: [
            {
              time: "2nd Game PM",
              tbd: true,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "6th Game PM",
              tbd: true,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
      ],
    },
    {
      day: 19,
      name: "Thursday",
      date: "March 19, 2026",
      sections: [
        {
          sport: "basketball",
          icon: "ico-basketball",
          label: "Basketball — Men (5v5)",
          venue: "UDD Quadrangle",
          highlight: null,
          matches: [
            {
              time: "11:00 AM",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 74, opp: 56 },
            },
            {
              time: "4:00 PM",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 75, opp: 77 },
            },
          ],
        },
        {
          sport: "basketball",
          icon: "ico-basketball",
          label: "Basketball — Women (3v3)",
          venue: "LCR Gym Court #1",
          highlight: null,
          matches: [
            {
              time: "8:15 AM",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 3, opp: 12 },
            },
            {
              time: "9:15 AM",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 4, opp: 3 },
            },
            {
              time: "10:00 AM",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 10, opp: 8 },
            },
            {
              time: "10:30 AM",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 6, opp: 5 },
            },
            {
              time: "11:00 AM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "1:15 PM",
              tbd: null,
              opp: "CISTE",
              stage: "semis",
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "2:00 PM",
              tbd: null,
              opp: "SBA",
              stage: "3rd",
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "volleyball",
          icon: "ico-volleyball",
          label: "Volleyball — Men",
          venue: "Leisure Coast Court 1",
          highlight: null,
          matches: [
            {
              time: "3rd Game AM",
              tbd: true,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 2, opp: 1 },
            },
            {
              time: "3rd Game PM",
              tbd: true,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 1, opp: 2 },
            },
          ],
        },
        {
          sport: "volleyball",
          icon: "ico-volleyball",
          label: "Volleyball — Women",
          venue: "Leisure Coast Court 2",
          highlight: null,
          matches: [
            {
              time: "3rd Game AM",
              tbd: true,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 1, opp: 2 },
            },
            {
              time: "3rd Game PM",
              tbd: true,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 0, opp: 2 },
            },
          ],
        },
        {
          sport: "beach",
          icon: "ico-beach",
          label: "Beach Volleyball — Women",
          venue: "Sand Area",
          highlight: null,
          matches: [
            {
              time: "2nd Game AM",
              tbd: true,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "6th Game AM",
              tbd: true,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "beach",
          icon: "ico-beach",
          label: "Beach Volleyball — Men",
          venue: "Sand Area",
          highlight: null,
          matches: [
            {
              time: "3rd Game PM",
              tbd: true,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "5th Game PM",
              tbd: true,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "chess",
          icon: "ico-chess",
          label: "Chess — Men (Individual)",
          venue: "Library · VPA Building",
          highlight: null,
          matches: [
            {
              time: "8:30 AM",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "10:30 AM",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "1:00 PM",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "2:00 PM",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "3:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "4:30 PM",
              tbd: null,
              opp: "SOHS",
              stage: "semis",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "After Semis",
              tbd: true,
              opp: "SOHE",
              stage: "finals",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "chess",
          icon: "ico-chess",
          label: "Chess — Women (Individual)",
          venue: "Library · VPA Building",
          highlight: null,
          matches: [
            {
              time: "8:30 AM",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "10:30 AM",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "1:00 PM",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "2:00 PM",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "3:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "4:30 PM",
              tbd: null,
              opp: "SOHS",
              stage: "semis",
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "After Semis",
              tbd: true,
              opp: "SOHE",
              stage: "3rd",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
          ],
        },
      ],
    },
    {
      day: 23,
      name: "Monday",
      date: "March 23, 2026",
      sections: [
        {
          sport: "basketball",
          icon: "ico-basketball",
          label: "Basketball — Men (5v5)",
          venue: "UDD Quadrangle",
          highlight: null,
          matches: [
            {
              time: "9:30 AM",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 82, opp: 52 },
            },
            {
              time: "1:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "volleyball",
          icon: "ico-volleyball",
          label: "Volleyball — Men",
          venue: "Leisure Coast Court 1",
          highlight: null,
          matches: [
            {
              time: "2nd Game AM",
              tbd: true,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 2, opp: 1 },
            },
            {
              time: "1:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "volleyball",
          icon: "ico-volleyball",
          label: "Volleyball — Women",
          venue: "Leisure Coast Court 2",
          highlight: null,
          matches: [
            {
              time: "2nd Game AM",
              tbd: true,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 2, opp: 0 },
            },
            {
              time: "1:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 0, opp: 2 },
            },
          ],
        },
        {
          sport: "beach",
          icon: "ico-beach",
          label: "Beach Volleyball — Women",
          venue: "Sand Area",
          highlight: null,
          matches: [
            {
              time: "3rd Game AM",
              tbd: true,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 15, opp: 30 },
            },
            {
              time: "5th Game AM",
              tbd: true,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 16, opp: 30 },
            },
            {
              time: "3:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 28, opp: 30 },
            },
          ],
        },
        {
          sport: "beach",
          icon: "ico-beach",
          label: "Beach Volleyball — Men",
          venue: "Sand Area",
          highlight: null,
          matches: [
            {
              time: "1:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "scrabble",
          icon: "ico-scrabble",
          label: "Scrabble — Men (Singles)",
          venue: "Library",
          highlight: null,
          matches: [
            {
              time: "8:30 AM",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "9:55 AM",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "10:55 AM",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "11:30 AM",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "1:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "scrabble",
          icon: "ico-scrabble",
          label: "Scrabble — Women (Singles)",
          venue: "Library",
          highlight: null,
          matches: [
            {
              time: "8:30 AM",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "9:55 AM",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "11:55 AM",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "1:30 PM",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "2:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "scrabble",
          icon: "ico-scrabble",
          label: "Scrabble — Mixed Doubles",
          venue: "Library",
          highlight: null,
          matches: [
            {
              time: "3:30 PM",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "3:55 PM",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "4:55 PM",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "mobilelegends",
          icon: "ico-mobilelegends",
          label: "Mobile Legends",
          venue: "L301 & L302",
          highlight: null,
          matches: [
            {
              time: "8:00 AM",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "9:00 AM",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "10:00 AM",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "11:00 AM",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "1:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "callofduty",
          icon: "ico-callofduty",
          label: "Call of Duty Mobile",
          venue: "L301 & L302",
          highlight: null,
          matches: [
            {
              time: "8:00 AM",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 3, opp: 0 },
            },
            {
              time: "9:00 AM",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 3, opp: 0 },
            },
            {
              time: "10:00 AM",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 2, opp: 1 },
            },
            {
              time: "11:00 AM",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 3, opp: 0 },
            },
            {
              time: "1:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 3, opp: 0 },
            },
          ],
        },
      ],
    },
    {
      day: 24,
      name: "Tuesday",
      date: "March 24, 2026",
      sections: [
        {
          sport: "volleyball",
          icon: "ico-volleyball",
          label: "Volleyball — Men",
          venue: "UDD Quadrangle",
          highlight: null,
          matches: [
            {
              time: "1:00 PM",
              tbd: null,
              opp: "SIHM",
              stage: "3rd",
              bracket: null,
              result: "win",
              score: { site: 2, opp: 0 },
            },
          ],
        },
        {
          sport: "scrabble",
          icon: "ico-scrabble",
          label: "Scrabble — Mixed Doubles",
          venue: "Library",
          highlight: null,
          matches: [
            {
              time: "8:00 AM",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "8:30 AM",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "scrabble",
          icon: "ico-scrabble",
          label: "Scrabble — Men (Singles)",
          venue: "Library",
          highlight: null,
          matches: [
            {
              time: "9:00 AM",
              tbd: null,
              opp: "SOHE",
              stage: "quarters",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "9:30 AM",
              tbd: null,
              opp: "SIHM",
              stage: "semis",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "9:55 AM",
              tbd: null,
              opp: "SBA",
              stage: "finals",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "scrabble",
          icon: "ico-scrabble",
          label: "Scrabble — Women (Singles)",
          venue: "Library",
          highlight: null,
          matches: [
            {
              time: "9:30 AM",
              tbd: null,
              opp: "SIHM",
              stage: "semis",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "9:55 AM",
              tbd: null,
              opp: "SBA",
              stage: "finals",
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "tabletennis",
          icon: "ico-tabletennis",
          label: "Table Tennis — Men",
          venue: "Niki's Garden",
          highlight: null,
          matches: [
            {
              time: "Game 2",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 6",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "Game 9",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 11",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 13",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "PM",
              tbd: null,
              opp: "SOHS",
              stage: "semis",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "PM",
              tbd: null,
              opp: "SOHE",
              stage: "finals",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "tabletennis",
          icon: "ico-tabletennis",
          label: "Table Tennis — Women",
          venue: "Niki's Garden",
          highlight: null,
          matches: [
            {
              time: "Game 2",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 6",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 9",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "Game 11",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 13",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "PM",
              tbd: null,
              opp: "SIHM",
              stage: "semis",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "PM",
              tbd: null,
              opp: "SOHS",
              stage: "finals",
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "tabletennis",
          icon: "ico-tabletennis",
          label: "Table Tennis — Mixed Doubles",
          venue: "Niki's Garden",
          highlight: null,
          matches: [
            {
              time: "Game 2",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 6",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 9",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "Game 11",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 13",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "PM",
              tbd: null,
              opp: "SOHE",
              stage: "semis",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "PM",
              tbd: null,
              opp: "SOHS",
              stage: "finals",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "mobilelegends",
          icon: "ico-mobilelegends",
          label: "Mobile Legends",
          venue: "Audio-Visual Theater",
          highlight: null,
          matches: [
            {
              time: "9:00 AM",
              tbd: null,
              opp: "SOHS",
              stage: "semis",
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "1:00 PM",
              tbd: null,
              opp: "SBA",
              stage: "finals",
              bracket: false,
              result: "win",
              score: { site: 3, opp: 1 },
            },
          ],
        },
        {
          sport: "callofduty",
          icon: "ico-callofduty",
          label: "Call of Duty Mobile",
          venue: "Audio-Visual Theater",
          highlight: null,
          matches: [
            {
              time: "9:00 AM",
              tbd: null,
              opp: "SBA",
              stage: "semis",
              bracket: null,
              result: "win",
              score: { site: 2, opp: 0 },
            },
            {
              time: "4:00 PM",
              tbd: null,
              opp: "SOHS",
              stage: "finals",
              bracket: false,
              result: "win",
              score: { site: null, opp: null },
            },
          ],
        },
      ],
    },
    {
      day: 25,
      name: "Wednesday",
      date: "March 25, 2026",
      sections: [
        {
          sport: "badminton",
          icon: "ico-badminton",
          label: "Badminton — Men",
          venue: "Niki's Garden",
          highlight: true,
          matches: [
            {
              time: "Game 4",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 1, opp: 2 },
            },
            {
              time: "Game 16",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 2, opp: 0 },
            },
          ],
        },
        {
          sport: "badminton",
          icon: "ico-badminton",
          label: "Badminton — Women",
          venue: "Niki's Garden",
          highlight: true,
          matches: [
            {
              time: "Game 5",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 0, opp: 2 },
            },
            {
              time: "Game 17",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: 0, opp: 2 },
            },
          ],
        },
        {
          sport: "badminton",
          icon: "ico-badminton",
          label: "Badminton — Mixed Doubles",
          venue: "Niki's Garden",
          highlight: true,
          matches: [
            {
              time: "Game 6",
              tbd: null,
              opp: "CISTE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 2, opp: 0 },
            },
            {
              time: "Game 18",
              tbd: null,
              opp: "SOHE",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: 2, opp: 0 },
            },
          ],
        },
        {
          sport: "basketball",
          icon: "ico-basketball",
          label: "Basketball — Men (5v5)",
          venue: "UDD Quadrangle",
          highlight: null,
          matches: [
            {
              time: "8:00 AM",
              tbd: null,
              opp: "???",
              stage: "semis",
              bracket: false,
              result: null,
              score: { site: null, opp: null },
            },
            {
              time: "1:30 PM",
              tbd: null,
              opp: "???",
              stage: "3rd",
              bracket: true,
              result: null,
              score: { site: null, opp: null },
            },
          ],
        },
      ],
    },
    {
      day: 26,
      name: "Thursday",
      date: "March 26, 2026",
      sections: [
        {
          sport: "badminton",
          icon: "ico-badminton",
          label: "Badminton — Men",
          venue: "Smashzone",
          highlight: true,
          matches: [
            {
              time: "Game 2",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "Game 4",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 6",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: null,
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "badminton",
          icon: "ico-badminton",
          label: "Badminton — Women",
          venue: "Smashzone",
          highlight: true,
          matches: [
            {
              time: "Game 2",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "lose",
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "Game 4",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "lose",
              result: "lose",
              score: { site: null, opp: null },
            },
            {
              time: "Game 6",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: null,
              score: { site: null, opp: null },
            },
            {
              time: "After Elim.",
              tbd: null,
              opp: "???",
              stage: "semis",
              bracket: true,
              result: null,
              score: { site: null, opp: null },
            },
            {
              time: "After Semis",
              tbd: null,
              opp: "???",
              stage: "3rd",
              bracket: true,
              result: null,
              score: { site: null, opp: null },
            },
            {
              time: "After Battle",
              tbd: null,
              opp: "???",
              stage: "finals",
              bracket: true,
              result: null,
              score: { site: null, opp: null },
            },
          ],
        },
        {
          sport: "badminton",
          icon: "ico-badminton",
          label: "Badminton — Mixed Doubles",
          venue: "Smashzone",
          highlight: true,
          matches: [
            {
              time: "Game 2",
              tbd: null,
              opp: "SOHS",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 4",
              tbd: null,
              opp: "SBA",
              stage: null,
              bracket: null,
              result: "win",
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "Game 6",
              tbd: null,
              opp: "SIHM",
              stage: null,
              bracket: null,
              result: "win",
              score: { site: null, opp: null },
            },
            {
              time: "After Elim.",
              tbd: null,
              opp: "???",
              stage: "semis",
              bracket: true,
              result: null,
              score: { site: null, opp: null },
            },
            {
              time: "After Semis",
              tbd: null,
              opp: "???",
              stage: "3rd",
              bracket: true,
              result: null,
              score: { site: null, opp: null },
            },
            {
              time: "After Battle",
              tbd: null,
              opp: "???",
              stage: "finals",
              bracket: true,
              result: null,
              score: { site: null, opp: null },
            },
          ],
        },
      ],
    },
  ],
};

// ── TALLY META ──
// semis / finals: "win" | "lose" | null (null = not yet played / N/A)
// result: "Champion" | "Runner-up" | "3rd Place" | any string | null
// semis / finals results are derived automatically from matches with stage: "semis"/"finals" in SCHEDULE_DATA.
// Only set result here: "Champion" | "Runner-up" | "3rd Place" | null
const TALLY_META = {
  "Basketball — Men (5v5)": { result: "3rd Place" },
  "Basketball — Women (3v3)": { result: "4th Place" },
  "Volleyball — Men": { result: "3rd Place" },
  "Volleyball — Women": { result: "5th Place" },
  "Beach Volleyball — Men": { result: "6th Place" },
  "Beach Volleyball — Women": { result: "5th Place" },
  "Chess — Men (Individual)": { result: "Champion" },
  "Chess — Women (Individual)": { result: "3rd Place" },
  "Scrabble — Men (Singles)": { result: "Champion" },
  "Scrabble — Women (Singles)": { result: "2nd Place" },
  "Scrabble — Mixed Doubles": { result: "5th Place" },
  "Table Tennis — Men": { result: "Champion" },
  "Table Tennis — Women": { result: "2nd Place" },
  "Table Tennis — Mixed Doubles": { result: "Champion" },
  "Badminton — Men": { result: null },
  "Badminton — Women": { result: null },
  "Badminton — Mixed Doubles": { result: null },
  "Mobile Legends": { result: "Champion" },
  "Call of Duty Mobile": { result: "Champion" },
};
